#!/usr/bin/env python3
"""The /t/<CODE> short link, the ?code= handling on every buy button, and the redirect rule."""

import pathlib
import re
import sys
import unittest

ROOT = pathlib.Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "build"))

import build as site_build  # noqa: E402
import shell  # noqa: E402


class TicketLinks(unittest.TestCase):
    def test_redirect_rule_is_generated_not_hand_edited(self):
        rules = site_build.redirects_file()
        self.assertIn("/t/:code  /pricing?code=:code  302", rules)
        self.assertIn("Generated by build/build.py", rules)
        built = (ROOT / "site" / "_redirects").read_text()
        self.assertIn("/t/:code  /pricing?code=:code  302", built)

    def test_every_buy_button_carries_the_code_line_and_copy(self):
        html = shell.buy_button("class", "Buy", "t")
        self.assertIn('class="buy-code"', html)
        self.assertIn("hidden", html)
        self.assertIn("Code {code} applied at checkout", html)
        self.assertIn("That code is no longer valid", html)

    def test_script_validates_stores_shows_and_sends_the_code(self):
        js = shell.body_script()
        self.assertIn(r"/^CI\d{2}-?[A-Z0-9]{6}$/i", js)
        self.assertIn("sessionStorage.setItem('mci_ticket_code'", js)
        self.assertIn("payload.code = ticketCode", js)
        self.assertIn("code_status === 'invalid'", js)

    def test_pages_with_a_buy_button_have_the_script(self):
        for page in ("pricing.html", "index.html"):
            html = (ROOT / "site" / page).read_text()
            self.assertIn("mci_ticket_code", html, page)
            self.assertRegex(html, r'class="buy-code"[^>]*hidden', page)


class InlineScriptsParse(unittest.TestCase):
    """A broken inline script silently kills every handler on the page (it once took the
    buy buttons down), so every distinct inline script on the built site must parse."""

    def test_every_inline_script_parses(self):
        import shutil
        import subprocess
        import tempfile

        node = shutil.which("node")
        if not node:
            self.skipTest("node not installed")
        scripts = {}
        for page in (ROOT / "site").rglob("*.html"):
            for body in re.findall(r"<script>(.*?)</script>", page.read_text(), re.S):
                scripts.setdefault(body, page.name)
        self.assertGreater(len(scripts), 0)
        with tempfile.TemporaryDirectory() as tmp:
            for i, (body, name) in enumerate(scripts.items()):
                path = pathlib.Path(tmp) / f"s{i}.js"
                path.write_text(body)
                result = subprocess.run([node, "--check", str(path)], capture_output=True, text=True)
                self.assertEqual(result.returncode, 0, f"inline script from {name} does not parse: {result.stderr[:300]}")


if __name__ == "__main__":
    unittest.main()
