#!/usr/bin/env python3
"""The /t/<CODE> short link, the ?code= handling on every buy button, and the redirect rule."""

import pathlib
import re
import sys
import unittest

ROOT = pathlib.Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "build"))

import build as site_build  # noqa: E402
import shell  # noqa: E402


class TicketLinks(unittest.TestCase):
    def test_short_link_is_a_rewrite_generated_not_hand_edited(self):
        rules = site_build.redirects_file()
        self.assertIn("/t/*  /t/  200", rules)
        self.assertNotIn(":code", [l for l in rules.splitlines() if not l.startswith("#")].__str__())
        self.assertIn("Generated by build/build.py", rules)
        built = (ROOT / "site" / "_redirects").read_text()
        self.assertIn("/t/*  /t/  200", built)
        self.assertNotRegex(built, r"(?m)^/t/:code")

    def test_short_link_page_is_noindex_and_not_in_the_sitemap(self):
        html = (ROOT / "site" / "t" / "index.html").read_text()
        self.assertIn('<meta name="robots" content="noindex, nofollow">', html)
        self.assertIn('<a href="/pricing">Continue to tickets</a>', html)
        self.assertNotIn("<nav", html)
        self.assertNotIn("/t/", (ROOT / "site" / "sitemap.xml").read_text())
        self.assertIn("/t/*", (ROOT / "site" / "_headers").read_text())

    def test_every_buy_button_carries_the_code_line_and_copy(self):
        html = shell.buy_button("class", "Buy", "t")
        self.assertIn('class="buy-code"', html)
        self.assertIn("hidden", html)
        self.assertIn("Code {code} applied at checkout", html)
        self.assertIn("That code is no longer valid", html)

    def test_script_validates_stores_shows_and_sends_the_code(self):
        js = shell.body_script()
        self.assertIn(r"/^CI\d{2}-?[A-Z0-9]{6}$/i", js)
        self.assertIn("sessionStorage.setItem('mci_ticket_code'", js)
        self.assertIn("payload.code = ticketCode", js)
        self.assertIn("code_status === 'invalid'", js)

    def test_pages_with_a_buy_button_have_the_script(self):
        for page in ("pricing.html", "index.html"):
            html = (ROOT / "site" / page).read_text()
            self.assertIn("mci_ticket_code", html, page)
            self.assertRegex(html, r'class="buy-code"[^>]*hidden', page)


class TicketPageScript(unittest.TestCase):
    """Run the page's own script in node with a stubbed `location` and read where it goes."""

    def _go(self, pathname):
        import json
        import shutil
        import subprocess

        node = shutil.which("node")
        if not node:
            self.skipTest("node not installed")
        html = (ROOT / "site" / "t" / "index.html").read_text()
        script = re.search(r"<script>(.*?)</script>", html, re.S).group(1)
        driver = (
            "var dest = null; var location = { pathname: %s, replace: function (u) { dest = u; } };"
            "(function () { %s })(); console.log(JSON.stringify(dest));" % (json.dumps(pathname), script)
        )
        out = subprocess.run([node, "-e", driver], capture_output=True, text=True)
        self.assertEqual(out.returncode, 0, out.stderr[:300])
        return json.loads(out.stdout)

    def test_script_parses(self):
        import shutil
        import subprocess
        import tempfile

        node = shutil.which("node")
        if not node:
            self.skipTest("node not installed")
        html = (ROOT / "site" / "t" / "index.html").read_text()
        script = re.search(r"<script>(.*?)</script>", html, re.S).group(1)
        with tempfile.TemporaryDirectory() as tmp:
            path = pathlib.Path(tmp) / "t.js"
            path.write_text(script)
            self.assertEqual(subprocess.run([node, "--check", str(path)], capture_output=True, text=True).returncode, 0)

    def test_valid_codes_go_to_pricing_with_the_code(self):
        self.assertEqual(self._go("/t/CI10K7P2QX"), "/pricing?code=CI10-K7P2QX")
        self.assertEqual(self._go("/t/CI10-K7P2QX"), "/pricing?code=CI10-K7P2QX")
        self.assertEqual(self._go("/t/ci20abcdef/"), "/pricing?code=CI20-ABCDEF")

    def test_anything_else_goes_to_plain_pricing(self):
        for path in ("/t/", "/t/index.html", "/t/garbage", "/t/CI1K7P2QX", "/t/CI10K7P2Q", "/t/CI10K7P2QXX", "/t/%E0%A4%A", "/t/CI10K7P2QX/extra"):
            self.assertEqual(self._go(path), "/pricing", path)


class InlineScriptsParse(unittest.TestCase):
    """A broken inline script silently kills every handler on the page (it once took the
    buy buttons down), so every distinct inline script on the built site must parse."""

    def test_every_inline_script_parses(self):
        import shutil
        import subprocess
        import tempfile

        node = shutil.which("node")
        if not node:
            self.skipTest("node not installed")
        scripts = {}
        for page in (ROOT / "site").rglob("*.html"):
            for body in re.findall(r"<script>(.*?)</script>", page.read_text(), re.S):
                scripts.setdefault(body, page.name)
        self.assertGreater(len(scripts), 0)
        with tempfile.TemporaryDirectory() as tmp:
            for i, (body, name) in enumerate(scripts.items()):
                path = pathlib.Path(tmp) / f"s{i}.js"
                path.write_text(body)
                result = subprocess.run([node, "--check", str(path)], capture_output=True, text=True)
                self.assertEqual(result.returncode, 0, f"inline script from {name} does not parse: {result.stderr[:300]}")


if __name__ == "__main__":
    unittest.main()
